"""

Password-based encryption and password hashing using Scrypt and Fernet via the cryptography library.
Encrypted tokens and password hashes are both stored as single opaque Base64 strings.

IMPORTANT: This encryption is only as strong as the password protecting it. Length matters much more than 
    complexity. Something like "BlueHorseBattery17" is good but a Diceware style passphrase is preferred. 

Orignial version based on: 
https://stackoverflow.com/questions/2490334/simple-way-to-encode-a-string-according-to-a-password#55147077
AI Disclosure: When rewriting this I did use GPT some.

Requires:
    cryptography
Optional:
    pyperclip

Usage: 
For text secrets, you can run this file directly for a token/hash creation wizard. 
Then, in your code:

import pbencrypt
token = 'bbDHosRjQ4Pd_Ft_BlNCIG83TVVhAxzFb4L6_s5AFtaAAAAAAGpOjptgecQJJ0EbM-8byK0926tcLqoNC18PFsRvAjgxlPUC2WBHv-NuZ3WCoJmP9HesOROPj_zN8SK5-pcPi9DoSW3thMONoa-XmwqEouBIBEn18mD_UVvG65BSE86CWLzdD_0='
pass_hash = 'OgWpMtwCxggMkdP4_Y8bnm6sYYd5vFTas64PN_vdz9XctkiBayDC3jKeCQ62GELRRyEFFSmFgQzhHTQtgzes4Q=='

# password is "pass"
password = input('>')

# returns true if password is correct
pbencrypt.vhash(pass_hash, password)

# returns decrypted secret
pbencrypt.decrypt(token, password).decode()

"""


__all__ = [
    "encrypt",
    "decrypt",
    "mhash",
    "vhash",
]


# pyperclip is lazy imported if used

import secrets
from base64 import urlsafe_b64decode as b64d
from base64 import urlsafe_b64encode as b64e

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives.constant_time import bytes_eq
from cryptography.hazmat.primitives.kdf.scrypt import Scrypt


SALT_SIZE = 32

# Scrypt parameters
# These are intentionally fairly expensive. Increase them over time as hardware improves.
SCRYPT_N = 2 ** 18
SCRYPT_R = 8
SCRYPT_P = 1
KEY_LENGTH = 32


# --------------------------------------------------------------------------------------------------------------------

def _new_scrypt(salt: bytes) -> Scrypt:
    return Scrypt(
        salt=salt,
        length=KEY_LENGTH,
        n=SCRYPT_N,
        r=SCRYPT_R,
        p=SCRYPT_P,
    )

def _derive_key(password: str, salt: bytes) -> bytes:
    # Derive a 32-byte key from a password using Scrypt.
    # Returns a Fernet-compatible Base64 key.
    kdf = _new_scrypt(salt)
    return b64e(kdf.derive(password.encode("utf-8")))


def encrypt(secret: bytes, password: str) -> bytes:
    # Encrypt bytes with a password.
    salt = secrets.token_bytes(SALT_SIZE)
    key = _derive_key(password, salt)
    encrypted = b64d(Fernet(key).encrypt(secret))
    return b64e(salt + encrypted)

def decrypt(token: bytes, password: str) -> bytes:
    # Decrypt a token generated by encrypt().
    decoded = b64d(token)
    salt = decoded[:SALT_SIZE]
    encrypted = b64e(decoded[SALT_SIZE:])
    key = _derive_key(password, salt)
    return Fernet(key).decrypt(encrypted)

def mhash(password: str) -> str:
    # Hash a password.
    salt = secrets.token_bytes(SALT_SIZE)
    kdf = _new_scrypt(salt)
    derived = kdf.derive(password.encode("utf-8"))
    return b64e(salt + derived).decode("ascii")

def vhash(stored_hash: str, password: str) -> bool:
    # Verify a password against a stored hash.
    decoded = b64d(stored_hash.encode("ascii"))
    salt = decoded[:SALT_SIZE]
    expected = decoded[SALT_SIZE:]
    kdf = _new_scrypt(salt)
    actual = kdf.derive(password.encode("utf-8"))
    return bytes_eq(actual, expected)

# --------------------------------------------------------------------------------------------------------------------


if __name__ == "__main__":
    
    print("\nCopy output to clipboard? Requires pyperclip. [Y/n]")
    response = input("> ").strip().lower()
    copy = response in ("", "y")
    if copy:
        try:
            import pyperclip
        except ImportError:
            pyperclip = None
            copy = False
            print("Failed to import pyperclip.")

    secret = input("\nSECRET>").encode()
    password = input("PASSWORD>")
    
    token = encrypt(secret, password)
    password_hash = mhash(password)
    
    decrypted = decrypt(token, password)
    verified = vhash(password_hash, password)
    
    if secret == decrypted and verified:
        print("\nTOKEN:")
        print(token.decode())
        print("\nPASSWORD HASH:")
        print(password_hash)

        if copy and pyperclip is not None:
            pyperclip.copy(token.decode())
            input("\nToken copied. Press Enter to copy password hash.")
            pyperclip.copy(password_hash)
            print("Password hash copied. Press Enter to exit.")
        else:
            print("\nPress Enter to exit.")
    
    else:
        if secret != decrypted:
            print("Decrypt test failed.")
        if not verified:
            print("Password hash verification failed.")
        print("Press Enter to exit.")
    input()

